name: 🐛 Bug Report
description: Create a report to help us improve OptiFork
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible.
        
        💡 **Tip**: Before submitting, please check if a similar issue already exists.

  - type: textarea
    id: description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 📋 Steps to Reproduce
      description: Detailed steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      description: A clear description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
      description: A clear description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots/Logs
      description: If applicable, add screenshots or logs to help explain your problem.
      placeholder: Paste screenshots or logs here...

  - type: dropdown
    id: deployment
    attributes:
      label: 🚀 Deployment Method
      description: How are you running OptiFork?
      options:
        - Docker Compose (Development)
        - Docker Compose (Production)
        - Manual Setup (Local)
        - Cloud Deployment
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 🧩 Affected Component
      description: Which part of OptiFork is affected?
      options:
        - Frontend (React UI)
        - Backend (FastAPI)
        - Database (PostgreSQL/SQLite)
        - Redis Cache
        - Docker/Deployment
        - API/Integration
        - Documentation
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 📦 OptiFork Version
      description: What version of OptiFork are you using?
      placeholder: "v1.0.0 or commit hash"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ Environment Details
      description: Please provide details about your environment.
      placeholder: |
        - OS: [e.g., Ubuntu 20.04, macOS 12.0, Windows 10]
        - Browser: [e.g., Chrome 95, Firefox 94, Safari 15]
        - Docker Version: [e.g., 20.10.8]
        - Python Version: [e.g., 3.9.7]
        - Node.js Version: [e.g., 16.13.0]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context about the problem here.
      placeholder: |
        Any additional information that might help:
        - Configuration settings
        - Error messages from logs
        - Workarounds you've tried
        - Related issues

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have provided a clear description of the problem
          required: true
        - label: I have included steps to reproduce the issue
          required: true
        - label: I have included relevant environment information
          required: true
        - label: I am willing to help test the fix when it's ready
          required: false